In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../data/raw/indian-job-market-dataset-2025.xlsx")

In [3]:
df.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [4]:
df.shape

(97929, 17)

In [5]:
df.columns

Index(['title', 'jobId', 'currency', 'jobUploaded', 'companyName',
       'tagsAndSkills', 'experience', 'salary', 'location', 'companyId',
       'ReviewsCount', 'AggregateRating', 'jobDescription', 'minimumSalary',
       'maximumSalary', 'minimumExperience', 'maximumExperience'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  str
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  str
 3   jobUploaded        97929 non-null  str
 4   companyName        97925 non-null  str
 5   tagsAndSkills      97358 non-null  str
 6   experience         95824 non-null  str
 7   salary             97929 non-null  str
 8   location           97929 non-null  str
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  str
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), str(9)
memory usage: 12.7 MB

In [7]:
df.isnull().sum()

title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(247)

In [9]:
df_clean = df.copy()

In [10]:
duplicate_rows = df_clean[df_clean.duplicated(keep=False)]

In [11]:
duplicate_rows.head(10)

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
99,Senior Executive - Research & Development,260925500768,INR,7 Days Ago,Bunge,"Senior Executive R&D,Microbiology,Food technol...",4-9 Yrs,Not disclosed,Rajpura,4124664,688.0,3.9,Minimum first class graduate in Food Technolog...,0.0,0.0,4.0,9.0
100,Senior Executive - Research & Development,260925500768,INR,7 Days Ago,Bunge,"Senior Executive R&D,Microbiology,Food technol...",4-9 Yrs,Not disclosed,Rajpura,4124664,688.0,3.9,Minimum first class graduate in Food Technolog...,0.0,0.0,4.0,9.0
199,Urgently looking For Preferred Head RM - PAN I...,260925009710,INR,7 Days Ago,AnandRathi,"Team Management,HNI/UHNI,New Client Acquisitio...",10-20 Yrs,30-45 Lacs PA,"Kochi, Chennai",69,251.0,3.5,Experienced professionals of more than 10 year...,3000000.0,4500000.0,10.0,20.0
200,Urgently looking For Preferred Head RM - PAN I...,260925009710,INR,7 Days Ago,AnandRathi,"Team Management,HNI/UHNI,New Client Acquisitio...",10-20 Yrs,30-45 Lacs PA,"Kochi, Chennai",69,251.0,3.5,Experienced professionals of more than 10 year...,3000000.0,4500000.0,10.0,20.0
1839,Chemical Engineer Trainee,300925926881,INR,3 Days Ago,TAJ Consultancy,"Operator,Chemical Engineering,Operations,Chemi...",0-5 Yrs,1.25-2.25 Lacs PA,Pune,835441,NaN,NaN,Wash And Rinse Reactors\n\nSupervise Chemical ...,125000.0,225000.0,0.0,5.0
1840,Chemical Engineer Trainee,300925926881,INR,3 Days Ago,TAJ Consultancy,"Operator,Chemical Engineering,Operations,Chemi...",0-5 Yrs,1.25-2.25 Lacs PA,Pune,835441,NaN,NaN,Wash And Rinse Reactors\n\nSupervise Chemical ...,125000.0,225000.0,0.0,5.0
1939,"Sr Quality / QMS Engineer , MNC",300925916981,INR,3 Days Ago,HR Innovation Group,"Quality Systems,IATF,QC Tools,Why-why Analysis...",6-11 Yrs,4.5-6 Lacs PA,Pune(Aundh +49),6398332,NaN,NaN,"Experience -08-10 yrs . skills - QMS,IATF,ISO,...",450000.0,600000.0,6.0,11.0
1940,"Sr Quality / QMS Engineer , MNC",300925916981,INR,3 Days Ago,HR Innovation Group,"Quality Systems,IATF,QC Tools,Why-why Analysis...",6-11 Yrs,4.5-6 Lacs PA,Pune(Aundh +49),6398332,NaN,NaN,"Experience -08-10 yrs . skills - QMS,IATF,ISO,...",450000.0,600000.0,6.0,11.0
2019,HR Manager,300925504838,INR,3 Days Ago,Tudip Technologies,"human capital,HR Executive,Legal compliance,Pe...",1-6 Yrs,Not disclosed,Pune,2041786,297.0,2.8,. Qualification Required: . Educational Qual...,0.0,0.0,1.0,6.0
2020,HR Manager,300925504838,INR,3 Days Ago,Tudip Technologies,"human capital,HR Executive,Legal compliance,Pe...",1-6 Yrs,Not disclosed,Pune,2041786,297.0,2.8,. Qualification Required: . Educational Qual...,0.0,0.0,1.0,6.0

In [12]:
duplicate_rows.shape

(494, 17)

In [13]:
df_clean = df.copy()

In [14]:
duplicate_rows = df_clean[df_clean.duplicated(keep=False)]

In [15]:
duplicate_rows.head(10)

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
99,Senior Executive - Research & Development,260925500768,INR,7 Days Ago,Bunge,"Senior Executive R&D,Microbiology,Food technol...",4-9 Yrs,Not disclosed,Rajpura,4124664,688.0,3.9,Minimum first class graduate in Food Technolog...,0.0,0.0,4.0,9.0
100,Senior Executive - Research & Development,260925500768,INR,7 Days Ago,Bunge,"Senior Executive R&D,Microbiology,Food technol...",4-9 Yrs,Not disclosed,Rajpura,4124664,688.0,3.9,Minimum first class graduate in Food Technolog...,0.0,0.0,4.0,9.0
199,Urgently looking For Preferred Head RM - PAN I...,260925009710,INR,7 Days Ago,AnandRathi,"Team Management,HNI/UHNI,New Client Acquisitio...",10-20 Yrs,30-45 Lacs PA,"Kochi, Chennai",69,251.0,3.5,Experienced professionals of more than 10 year...,3000000.0,4500000.0,10.0,20.0
200,Urgently looking For Preferred Head RM - PAN I...,260925009710,INR,7 Days Ago,AnandRathi,"Team Management,HNI/UHNI,New Client Acquisitio...",10-20 Yrs,30-45 Lacs PA,"Kochi, Chennai",69,251.0,3.5,Experienced professionals of more than 10 year...,3000000.0,4500000.0,10.0,20.0
1839,Chemical Engineer Trainee,300925926881,INR,3 Days Ago,TAJ Consultancy,"Operator,Chemical Engineering,Operations,Chemi...",0-5 Yrs,1.25-2.25 Lacs PA,Pune,835441,NaN,NaN,Wash And Rinse Reactors\n\nSupervise Chemical ...,125000.0,225000.0,0.0,5.0
1840,Chemical Engineer Trainee,300925926881,INR,3 Days Ago,TAJ Consultancy,"Operator,Chemical Engineering,Operations,Chemi...",0-5 Yrs,1.25-2.25 Lacs PA,Pune,835441,NaN,NaN,Wash And Rinse Reactors\n\nSupervise Chemical ...,125000.0,225000.0,0.0,5.0
1939,"Sr Quality / QMS Engineer , MNC",300925916981,INR,3 Days Ago,HR Innovation Group,"Quality Systems,IATF,QC Tools,Why-why Analysis...",6-11 Yrs,4.5-6 Lacs PA,Pune(Aundh +49),6398332,NaN,NaN,"Experience -08-10 yrs . skills - QMS,IATF,ISO,...",450000.0,600000.0,6.0,11.0
1940,"Sr Quality / QMS Engineer , MNC",300925916981,INR,3 Days Ago,HR Innovation Group,"Quality Systems,IATF,QC Tools,Why-why Analysis...",6-11 Yrs,4.5-6 Lacs PA,Pune(Aundh +49),6398332,NaN,NaN,"Experience -08-10 yrs . skills - QMS,IATF,ISO,...",450000.0,600000.0,6.0,11.0
2019,HR Manager,300925504838,INR,3 Days Ago,Tudip Technologies,"human capital,HR Executive,Legal compliance,Pe...",1-6 Yrs,Not disclosed,Pune,2041786,297.0,2.8,. Qualification Required: . Educational Qual...,0.0,0.0,1.0,6.0
2020,HR Manager,300925504838,INR,3 Days Ago,Tudip Technologies,"human capital,HR Executive,Legal compliance,Pe...",1-6 Yrs,Not disclosed,Pune,2041786,297.0,2.8,. Qualification Required: . Educational Qual...,0.0,0.0,1.0,6.0

In [16]:
df_clean = df_clean.drop_duplicates().copy()

In [17]:
df_clean.duplicated().sum()

np.int64(0)

In [18]:
df_clean.shape

(97682, 17)

In [19]:
df_clean["companyName"] = df_clean["companyName"].fillna("Unknown Company")

In [20]:
df_clean["companyName"].isnull().sum()

np.int64(0)

In [21]:
df_clean["companyName"] = df_clean["companyName"].fillna("Unknown Company")

In [22]:
df_clean["companyName"].isnull().sum()

np.int64(0)

In [23]:
df_clean[["experience", "minimumExperience", "maximumExperience"]].head(20)

   experience  minimumExperience  maximumExperience
0     2-4 Yrs                2.0                4.0
1    6-11 Yrs                6.0               11.0
2   12-18 Yrs               12.0               18.0
3     0-3 Yrs                0.0                3.0
4    5-10 Yrs                5.0               10.0
5   10-15 Yrs               10.0               15.0
6     3-5 Yrs                3.0                5.0
7     2-3 Yrs                2.0                3.0
8     2-4 Yrs                2.0                4.0
9    4-14 Yrs                4.0               14.0
10    0-4 Yrs                0.0                4.0
11   7-10 Yrs                7.0               10.0
12    0-4 Yrs                0.0                4.0
13    3-8 Yrs                3.0                8.0
14   8-10 Yrs                8.0               10.0
15    1-6 Yrs                1.0                6.0
16    2-7 Yrs                2.0                7.0
17    5-8 Yrs                5.0                8.0
18    3-7 Yrs                3.0                7.0
19   8-12 Yrs                8.0               12.0

In [24]:
df_clean[["experience", "minimumExperience", "maximumExperience"]].isnull().sum()

experience           2102
minimumExperience     571
maximumExperience     571
dtype: int64

In [25]:
df_clean.loc[
    df_clean["experience"].isnull(),
    ["title", "experience", "minimumExperience", "maximumExperience", "jobDescription"]
].head(10)

,title,experience,minimumExperience,maximumExperience,jobDescription
23,Walk In Drive @Noida | Quality Analyst | TELUS...,NaN,1.0,5.0,<p><u><strong>Role & Responsibilities</strong>...
152,Walk-in Drive - Relationship Manager - Nagpur,NaN,2.0,7.0,Preferred candidate profile <br><br>Min 2 - 8 ...
162,Assistant Manager / Deputy Manager,NaN,2.0,7.0,<p> </p><p><strong><u>Role & responsibilities:...
185,Front Office Executive,NaN,1.0,6.0,"Proficient in MS Office (Word,Excel)<br><br>Ca..."
211,Business Associate,NaN,0.0,1.0,Education: Any Graduate / Postgraduate <br><br...
217,PART TIME Associates,NaN,0.0,1.0,"Datamatics Global Services Ltd,Nashik is hirin..."
240,Product Designer Intern,NaN,NaN,NaN,<div> Location: Bangalore (Hybrid) | Experienc...
241,Intern,NaN,NaN,NaN,Willingness to work in laboratory shifts opera...
296,Mega Walk-In International Chat Process|| Noid...,NaN,0.0,4.0,Hiring for International Chat process . 5 days...
363,Trainee - Survey Research,NaN,NaN,NaN,. Must be comfortable traveling extensively a...

In [26]:
df_clean["experience_clean"] = df_clean["experience"]

In [27]:
mask = (
    df_clean["experience_clean"].isna()
    & df_clean["minimumExperience"].notna()
    & df_clean["maximumExperience"].notna()
)

df_clean.loc[mask, "experience_clean"] = (
    df_clean.loc[mask, "minimumExperience"].astype(int).astype(str)
    + "-"
    + df_clean.loc[mask, "maximumExperience"].astype(int).astype(str)
    + " Yrs"
)

In [28]:
df_clean["experience_clean"] = df_clean["experience_clean"].fillna(
    "Not Specified"
)

In [29]:
df_clean["experience_clean"].isna().sum()

np.int64(0)

In [30]:
df_clean["experience_clean"].value_counts().head(15)

experience_clean
5-10 Yrs    6480
3-8 Yrs     5788
1-3 Yrs     3999
2-5 Yrs     3810
1-6 Yrs     3733
2-7 Yrs     3673
0-5 Yrs     3438
3-5 Yrs     3298
5-8 Yrs     3280
1-5 Yrs     2979
4-9 Yrs     2892
0-1 Yrs     2694
1-4 Yrs     2486
0-2 Yrs     2411
6-11 Yrs    2383
Name: count, dtype: int64

In [1]:
df_clean["tagsAndSkills"].head(20)

NameError: name 'df_clean' is not defined

In [2]:
import pandas as pd
import numpy as np

# Load raw dataset
df = pd.read_excel("../data/raw/indian-job-market-dataset-2025.xlsx")

# Create working copy
df_clean = df.copy()

# Remove exact duplicate records
df_clean = df_clean.drop_duplicates().copy()

# Handle missing company names
df_clean["companyName"] = df_clean["companyName"].fillna("Unknown Company")

# Create standardized experience field
df_clean["experience_clean"] = df_clean["experience"]

mask = (
    df_clean["experience_clean"].isna()
    & df_clean["minimumExperience"].notna()
    & df_clean["maximumExperience"].notna()
)

df_clean.loc[mask, "experience_clean"] = (
    df_clean.loc[mask, "minimumExperience"].astype(int).astype(str)
    + "-"
    + df_clean.loc[mask, "maximumExperience"].astype(int).astype(str)
    + " Yrs"
)

df_clean["experience_clean"] = df_clean["experience_clean"].fillna(
    "Not Specified"
)

print("Dataset ready:", df_clean.shape)

Dataset ready: (97682, 18)

In [3]:
df_clean["tagsAndSkills"].head(20)

0     Communication,Manpower,Staffing,Convincing Pow...
1     Safety Officer Activities,Fire Protection,Fire...
2     Performance Marketing,User Acquisition,growth ...
3     Fluent English,Spoken English,Good English Com...
4     Product Marketing,CNS,Product Management,Nephr...
5     Tds Filing,ITR,Gst Filing,Balance Sheet Finali...
6     Booth,Conveyor,Special Process,Utility Mainten...
7     M.S Office,SAP,Computer Skills,MS Office,Techn...
8      SAP,Laboratory Knowledge,Microsoft,Technical,Lab
9     Sre,Azure Devops,Monitoring Tools,Site,Site Re...
10    BPO,Domestic Voice Process,Non Voice Process,D...
11    Blue Collar Hiring,Talent Acquisition,Recruitm...
12    Chat Support,US Process,Customer Support,Custo...
13    NBFC,Bulk Hiring,Sales Hiring,Non IT Recruitme...
14    Mep Billing Engineer,Mep Billing,Site Billing,...
15    Compliance Monitoring,Credit Card Fraud,Fraud ...
16    Fiber Optics,Ftth,Fttx,NLD,Deployment,Tower Er...
17    Mechanical,Billing,Planning,Billing Engineerin...
18    Tekla,AutoCAD,Mechanical Design,Solid Works,Bo...
19    Tekla,AutoCAD,Mechanical Design,Solid Works,Bo...
Name: tagsAndSkills, dtype: str

In [4]:
def clean_skills(value):
    if pd.isna(value):
        return []
    
    skills = str(value).split(",")
    
    skills = [
        skill.strip().lower()
        for skill in skills
        if skill.strip()
    ]
    
    return list(dict.fromkeys(skills))

In [5]:
df_clean["skills_clean"] = df_clean["tagsAndSkills"].apply(clean_skills)

In [6]:
df_clean[["tagsAndSkills", "skills_clean"]].head(10)

,tagsAndSkills,skills_clean
0,"Communication,Manpower,Staffing,Convincing Pow...","[communication, manpower, staffing, convincing..."
1,"Safety Officer Activities,Fire Protection,Fire...","[safety officer activities, fire protection, f..."
2,"Performance Marketing,User Acquisition,growth ...","[performance marketing, user acquisition, grow..."
3,"Fluent English,Spoken English,Good English Com...","[fluent english, spoken english, good english ..."
4,"Product Marketing,CNS,Product Management,Nephr...","[product marketing, cns, product management, n..."
5,"Tds Filing,ITR,Gst Filing,Balance Sheet Finali...","[tds filing, itr, gst filing, balance sheet fi..."
6,"Booth,Conveyor,Special Process,Utility Mainten...","[booth, conveyor, special process, utility mai..."
7,"M.S Office,SAP,Computer Skills,MS Office,Techn...","[m.s office, sap, computer skills, ms office, ..."
8,"SAP,Laboratory Knowledge,Microsoft,Technical,Lab","[sap, laboratory knowledge, microsoft, technic..."
9,"Sre,Azure Devops,Monitoring Tools,Site,Site Re...","[sre, azure devops, monitoring tools, site, si..."

In [7]:
def clean_skills(value):
    if pd.isna(value):
        return []
    
    skills = str(value).split(",")
    
    skills = [
        skill.strip().lower()
        for skill in skills
        if skill.strip()
    ]
    
    return list(dict.fromkeys(skills))

In [8]:
df_clean["skills_clean"] = df_clean["tagsAndSkills"].apply(clean_skills)

In [9]:
df_clean[["tagsAndSkills", "skills_clean"]].head(10)

,tagsAndSkills,skills_clean
0,"Communication,Manpower,Staffing,Convincing Pow...","[communication, manpower, staffing, convincing..."
1,"Safety Officer Activities,Fire Protection,Fire...","[safety officer activities, fire protection, f..."
2,"Performance Marketing,User Acquisition,growth ...","[performance marketing, user acquisition, grow..."
3,"Fluent English,Spoken English,Good English Com...","[fluent english, spoken english, good english ..."
4,"Product Marketing,CNS,Product Management,Nephr...","[product marketing, cns, product management, n..."
5,"Tds Filing,ITR,Gst Filing,Balance Sheet Finali...","[tds filing, itr, gst filing, balance sheet fi..."
6,"Booth,Conveyor,Special Process,Utility Mainten...","[booth, conveyor, special process, utility mai..."
7,"M.S Office,SAP,Computer Skills,MS Office,Techn...","[m.s office, sap, computer skills, ms office, ..."
8,"SAP,Laboratory Knowledge,Microsoft,Technical,Lab","[sap, laboratory knowledge, microsoft, technic..."
9,"Sre,Azure Devops,Monitoring Tools,Site,Site Re...","[sre, azure devops, monitoring tools, site, si..."

In [10]:
df_clean["skills_clean"].apply(len).value_counts().sort_index().head(10)

skills_clean
0      571
1      187
2      374
3      757
4     1119
5     1557
6     2159
7     2898
8    88060
Name: count, dtype: int64

In [11]:
df_clean[df_clean["skills_clean"].apply(len) == 0][
    ["title", "jobDescription"]
].head(10)

,title,jobDescription
240,Product Designer Intern,<div> Location: Bangalore (Hybrid) | Experienc...
241,Intern,Willingness to work in laboratory shifts opera...
363,Trainee - Survey Research,. Must be comfortable traveling extensively a...
418,HR Intern,"<p>1. Work on designing, updating descriptions..."
432,driven Professional,. Desired Qualifications & Key Competencies: ...
435,Trainee - Market Research,. Additional Requirement: . Must be comforta...
436,Trainee - Market Research,Nexdigm (SKP) is looking for Trainee - Market ...
613,Marketing Artist- Mobile Games,Experience: 0-1 Year. Company: Nukebox Studios...
734,Internship,Deyor Camps is looking for Internship to joi...
735,Marketing ( Intern ),Lighthouse Info Systems Pvt. Ltd. is looking ...

In [12]:
df_clean[df_clean["skills_clean"].apply(len) == 0][
    ["title", "jobDescription"]
].head(10)

,title,jobDescription
240,Product Designer Intern,<div> Location: Bangalore (Hybrid) | Experienc...
241,Intern,Willingness to work in laboratory shifts opera...
363,Trainee - Survey Research,. Must be comfortable traveling extensively a...
418,HR Intern,"<p>1. Work on designing, updating descriptions..."
432,driven Professional,. Desired Qualifications & Key Competencies: ...
435,Trainee - Market Research,. Additional Requirement: . Must be comforta...
436,Trainee - Market Research,Nexdigm (SKP) is looking for Trainee - Market ...
613,Marketing Artist- Mobile Games,Experience: 0-1 Year. Company: Nukebox Studios...
734,Internship,Deyor Camps is looking for Internship to joi...
735,Marketing ( Intern ),Lighthouse Info Systems Pvt. Ltd. is looking ...

In [13]:
df_clean["skills_clean"].apply(len).describe()

count    97682.000000
mean         7.710602
std          1.077299
min          0.000000
25%          8.000000
50%          8.000000
75%          8.000000
max          8.000000
Name: skills_clean, dtype: float64

In [14]:
df_clean["skills_clean"].apply(len).value_counts().sort_index()

skills_clean
0      571
1      187
2      374
3      757
4     1119
5     1557
6     2159
7     2898
8    88060
Name: count, dtype: int64

In [15]:
df_clean["skills_clean"].apply(len).describe()

count    97682.000000
mean         7.710602
std          1.077299
min          0.000000
25%          8.000000
50%          8.000000
75%          8.000000
max          8.000000
Name: skills_clean, dtype: float64

In [16]:
df_clean["skills_clean"].apply(len).value_counts().sort_index()

skills_clean
0      571
1      187
2      374
3      757
4     1119
5     1557
6     2159
7     2898
8    88060
Name: count, dtype: int64

In [18]:
df_clean["skills_clean"].apply(len).describe()

count    97682.000000
mean         7.710602
std          1.077299
min          0.000000
25%          8.000000
50%          8.000000
75%          8.000000
max          8.000000
Name: skills_clean, dtype: float64

In [19]:
df_clean["skills_clean"].apply(len).value_counts().sort_index()

skills_clean
0      571
1      187
2      374
3      757
4     1119
5     1557
6     2159
7     2898
8    88060
Name: count, dtype: int64

In [20]:
from collections import Counter

skill_counter = Counter(
    skill
    for skills in df_clean["skills_clean"]
    for skill in skills
)

skill_counter.most_common(20)

[('sales', 9178),
 ('python', 5846),
 ('project management', 5543),
 ('customer service', 5122),
 ('sap', 5043),
 ('management', 4849),
 ('css', 4186),
 ('java', 4088),
 ('sql', 3983),
 ('business development', 3738),
 ('communication skills', 3499),
 ('development', 3291),
 ('javascript', 3006),
 ('c#', 2978),
 ('troubleshooting', 2470),
 ('agile', 2459),
 ('marketing', 2441),
 ('accounting', 2426),
 ('english', 2273),
 ('automation', 2269)]

In [23]:
from collections import Counter

skill_counter = Counter(
    skill
    for skills in df_clean["skills_clean"]
    for skill in skills
)

skill_counter.most_common(20)

[('sales', 9178),
 ('python', 5846),
 ('project management', 5543),
 ('customer service', 5122),
 ('sap', 5043),
 ('management', 4849),
 ('css', 4186),
 ('java', 4088),
 ('sql', 3983),
 ('business development', 3738),
 ('communication skills', 3499),
 ('development', 3291),
 ('javascript', 3006),
 ('c#', 2978),
 ('troubleshooting', 2470),
 ('agile', 2459),
 ('marketing', 2441),
 ('accounting', 2426),
 ('english', 2273),
 ('automation', 2269)]

In [24]:
df_clean["title"].value_counts().head(20)

title
Application Developer             2033
Application Lead                  1346
Sales Executive                    576
Software Development Engineer      497
Business Development Executive     456
Trust & Safety New Associate       348
Data Engineer                      338
Business Development Manager       323
Sales Manager                      319
Java Full Stack Developer          282
Java Developer                     253
Relationship Manager               232
Area Sales Manager                 217
Application Support Engineer       217
Accountant                         215
Customer Support Executive         213
Senior Software Engineer           206
Account Executive                  205
Graphic Designer                   190
Software Development Lead          181
Name: count, dtype: int64

In [25]:
df_clean["title"].value_counts().head(20)

title
Application Developer             2033
Application Lead                  1346
Sales Executive                    576
Software Development Engineer      497
Business Development Executive     456
Trust & Safety New Associate       348
Data Engineer                      338
Business Development Manager       323
Sales Manager                      319
Java Full Stack Developer          282
Java Developer                     253
Relationship Manager               232
Area Sales Manager                 217
Application Support Engineer       217
Accountant                         215
Customer Support Executive         213
Senior Software Engineer           206
Account Executive                  205
Graphic Designer                   190
Software Development Lead          181
Name: count, dtype: int64

In [26]:
df_clean["location"].value_counts().head(20)

location
Bengaluru                        16783
Hyderabad                         7657
Pune                              6096
Chennai                           4418
Gurugram                          4226
Mumbai                            4149
Noida                             2688
Remote                            1952
Ahmedabad                         1721
Navi Mumbai                       1451
Kolkata                           1047
Hyderabad, Chennai, Bengaluru     1037
Hybrid - Bengaluru                 944
Jaipur                             815
Coimbatore                         618
Hybrid - Hyderabad                 575
Kochi                              526
Vadodara                           526
Hybrid - Pune                      478
Thane                              408
Name: count, dtype: int64

In [28]:
df_clean["minimumExperience"].value_counts().sort_index().head(15)

minimumExperience
0.0     12363
1.0     15311
2.0     12793
3.0     13575
4.0      7474
5.0     12264
6.0      5268
7.0      4021
8.0      4484
9.0       914
10.0     3581
11.0      248
12.0     1403
13.0      285
14.0      210
Name: count, dtype: int64

In [29]:
df_clean["maximumExperience"].value_counts().sort_index().head(15)

maximumExperience
0.0       532
1.0      2719
2.0      4304
3.0      7246
4.0      6324
5.0     13903
6.0      9077
7.0      8017
8.0     11740
9.0      4672
10.0    10015
11.0     3202
12.0     3820
13.0     2365
14.0     1026
Name: count, dtype: int64

In [30]:
# cateogorising the roles
def classify_role(title):
    title = str(title).lower()

    if any(x in title for x in [
        "data engineer", "data engineering", "etl",
        "big data", "data warehouse", "data platform"
    ]):
        return "Data Engineering"

    elif any(x in title for x in [
        "data analyst", "business analyst", "bi analyst",
        "business intelligence", "reporting analyst"
    ]):
        return "Data Analytics"

    elif any(x in title for x in [
        "machine learning", "machine learning engineer",
        "ai engineer", "artificial intelligence",
        "ml engineer", "deep learning", "nlp"
    ]):
        return "AI / ML"

    elif any(x in title for x in [
        "software engineer", "software developer",
        "application developer", "java developer",
        "python developer", "full stack", "backend",
        "frontend", "web developer"
    ]):
        return "Software Development"

    elif any(x in title for x in [
        "devops", "cloud engineer", "cloud",
        "site reliability", "sre", "infrastructure"
    ]):
        return "Cloud / DevOps"

    else:
        return "Other"

In [31]:
df_clean["role_category"] = df_clean["title"].apply(classify_role)

In [32]:
df_clean["role_category"].value_counts()

role_category
Other                   86529
Software Development     6675
Cloud / DevOps           1732
Data Engineering         1329
Data Analytics            849
AI / ML                   568
Name: count, dtype: int64

In [33]:
candidate_skills = [
    "python",
    "sql",
    "pandas",
    "power bi"
]

candidate_role = "Data Engineering"
candidate_location = "Hyderabad"
candidate_experience = 0

In [34]:
candidate_jobs = df_clean[
    (df_clean["role_category"] == candidate_role) &
    (df_clean["minimumExperience"] <= candidate_experience + 1)
].copy()

In [35]:
candidate_jobs.shape

(33, 20)

In [36]:
def calculate_skill_match(job_skills, candidate_skills):
    if not job_skills:
        return 0
    
    matched = set(job_skills) & set(candidate_skills)
    return round((len(matched) / len(set(job_skills))) * 100, 2)

In [38]:
candidate_jobs["skill_match"] = candidate_jobs["skills_clean"].apply(
    lambda x: calculate_skill_match(x, candidate_skills)
)

In [39]:
candidate_jobs = candidate_jobs.sort_values(
    "skill_match",
    ascending=False
)

In [40]:
candidate_jobs[
    ["title", "companyName", "location", "skills_clean", "skill_match"]
].head(10)

,title,companyName,location,skills_clean,skill_match
4078,Data Engineer|L1 Support|Noida,Talentonlease,"Noida, Mumbai","[etl, elt, aws, python, sql, data, l1, data en...",25.0
71725,Senior Data Engineer,Quantiphi Analytics Solutions,Thiruvananthapuram,"[bigquery, sql, gcp, etl, python, data, senior...",25.0
8653,Big Data Engineer,Techno Facts Solutions,Remote,"[sql, git, data engineer, aws, python, airflow...",25.0
10338,Trainee/Junior Data Engineer,Contata Solutions,Noida,"[python basics, sql, git, python ide, cloud, v...",25.0
22795,Data Engineer For Private Bank One Data Platfo...,Deutsche Bank,Pune,"[continuous integration, python, ci/cd, sql, n...",25.0
33882,Intern - Data Engineering,Exponentia Datalabs,Mumbai,"[analytical & problem-solving ability, python,...",25.0
41423,Data Engineer,Seven N Consulting,Bengaluru,"[hive, snowflake, python, data analytics, data...",25.0
22901,Fixed Income Data Engineer,MSCI Services,Pune,"[continuous integration, python, oracle, java,...",25.0
45144,Data Engineer - Snowflake,Prudent Globaltech Solutions,Hyderabad,"[snowflake, sql queries, sql server, sql, etl ...",25.0
52712,Trainee Data Engineer,Leewayhertz Technologies,Gurugram,"[data engineering, data engineer, aws, python,...",25.0

In [41]:
def location_score(job_location, candidate_location):
    job_location = str(job_location).lower()
    candidate_location = candidate_location.lower()

    if candidate_location in job_location:
        return 100
    elif "remote" in job_location:
        return 80
    else:
        return 0

In [42]:
candidate_jobs["location_score"] = candidate_jobs["location"].apply(
    lambda x: location_score(x, candidate_location)
)

In [43]:
def experience_score(min_exp, candidate_exp):
    if pd.isna(min_exp):
        return 50
    
    if min_exp <= candidate_exp:
        return 100
    elif min_exp == candidate_exp + 1:
        return 80
    elif min_exp == candidate_exp + 2:
        return 50
    else:
        return 20

In [44]:
candidate_jobs["experience_score"] = candidate_jobs[
    "minimumExperience"
].apply(
    lambda x: experience_score(x, candidate_experience)
)

In [45]:
candidate_jobs["final_score"] = (
    candidate_jobs["skill_match"] * 0.60
    + candidate_jobs["location_score"] * 0.25
    + candidate_jobs["experience_score"] * 0.15
)

In [46]:
candidate_jobs = candidate_jobs.sort_values(
    "final_score",
    ascending=False
)

In [47]:
candidate_jobs[
    [
        "title",
        "companyName",
        "location",
        "skill_match",
        "location_score",
        "experience_score",
        "final_score"
    ]
].head(10)

,title,companyName,location,skill_match,location_score,experience_score,final_score
45144,Data Engineer - Snowflake,Prudent Globaltech Solutions,Hyderabad,25.00,100,80,52.000
44126,Opening For ETL Tester in Hyderabad location (...,Enrich And Enlight Business Consulting,Hyderabad,20.00,100,80,49.000
6546,Data Engineer Associate,Elfonze Technologies,"Hyderabad, Bengaluru",12.50,100,100,47.500
8653,Big Data Engineer,Techno Facts Solutions,Remote,25.00,80,80,47.000
60451,Data Engineer at An E-commerce Unicorn,Recruito,Remote,14.29,80,80,40.574
86049,Data Engineer/ Analyst,Info Origin,Hyderabad,0.00,100,100,40.000
77627,Kafka /Streaming Data Engineer,Nexure Tech,"Visakhapatnam, Warangal, Hyderabad",0.00,100,100,40.000
6918,Data Engineer Freshers,Arccaa Analytics And It Solutions,Hyderabad,0.00,100,100,40.000
9145,Data Engineer,Amgen Inc,Hyderabad,0.00,100,80,37.000
52712,Trainee Data Engineer,Leewayhertz Technologies,Gurugram,25.00,0,100,30.000

In [48]:
candidate_jobs = candidate_jobs[
    candidate_jobs["skill_match"] > 0
].copy()

In [49]:
candidate_jobs["final_score"] = (
    candidate_jobs["skill_match"] * 0.70
    + candidate_jobs["experience_score"] * 0.20
    + candidate_jobs["location_score"] * 0.10
)

In [50]:
candidate_jobs = candidate_jobs.sort_values(
    "final_score",
    ascending=False
)

In [52]:
candidate_jobs[
    [
        "title",
        "companyName",
        "location",
        "skill_match",
        "location_score",
        "experience_score",
        "final_score"
    ]
].head(10)

,title,companyName,location,skill_match,location_score,experience_score,final_score
45144,Data Engineer - Snowflake,Prudent Globaltech Solutions,Hyderabad,25.00,100,80,43.500
8653,Big Data Engineer,Techno Facts Solutions,Remote,25.00,80,80,41.500
44126,Opening For ETL Tester in Hyderabad location (...,Enrich And Enlight Business Consulting,Hyderabad,20.00,100,80,40.000
6546,Data Engineer Associate,Elfonze Technologies,"Hyderabad, Bengaluru",12.50,100,100,38.750
52712,Trainee Data Engineer,Leewayhertz Technologies,Gurugram,25.00,0,100,37.500
33882,Intern - Data Engineering,Exponentia Datalabs,Mumbai,25.00,0,100,37.500
80565,Business Technology Solutions Associate_ Cloud...,ZS,Pune,25.00,0,100,37.500
10338,Trainee/Junior Data Engineer,Contata Solutions,Noida,25.00,0,100,37.500
60451,Data Engineer at An E-commerce Unicorn,Recruito,Remote,14.29,80,80,34.003
4078,Data Engineer|L1 Support|Noida,Talentonlease,"Noida, Mumbai",25.00,0,80,33.500

In [53]:
def get_skill_gaps(job_skills, candidate_skills):
    job_set = set(job_skills)
    candidate_set = set(candidate_skills)

    return sorted(job_set - candidate_set)

In [54]:
candidate_jobs["skill_gaps"] = candidate_jobs["skills_clean"].apply(
    lambda x: get_skill_gaps(x, candidate_skills)
)

In [55]:
candidate_jobs[
    ["title", "companyName", "skill_match", "skill_gaps"]
].head(10)

,title,companyName,skill_match,skill_gaps
45144,Data Engineer - Snowflake,Prudent Globaltech Solutions,25.00,"[data manipulation, data warehousing, etl tool..."
8653,Big Data Engineer,Techno Facts Solutions,25.00,"[airflow, aws, data engineer, git, github, orc..."
44126,Opening For ETL Tester in Hyderabad location (...,Enrich And Enlight Business Consulting,20.00,"[api, etl, etl testing, software testing]"
6546,Data Engineer Associate,Elfonze Technologies,12.50,"[data governance, data integrity, data managem..."
52712,Trainee Data Engineer,Leewayhertz Technologies,25.00,"[aws, data engineer, data engineering, data pi..."
33882,Intern - Data Engineering,Exponentia Datalabs,25.00,"[analytical & problem-solving ability, analyti..."
80565,Business Technology Solutions Associate_ Cloud...,ZS,25.00,"[media, microservices, microsoft azure, rdbms,..."
10338,Trainee/Junior Data Engineer,Contata Solutions,25.00,"[bigquery fundamentals, cloud, git, python bas..."
60451,Data Engineer at An E-commerce Unicorn,Recruito,14.29,"[bricks, data, data bricks, e-commerce, kafka,..."
4078,Data Engineer|L1 Support|Noida,Talentonlease,25.00,"[aws, data, data engineering, elt, etl, l1]"

In [56]:
recommendations = candidate_jobs[
    [
        "title",
        "companyName",
        "location",
        "skill_match",
        "experience_score",
        "location_score",
        "final_score",
        "skill_gaps"
    ]
].head(10).copy()

In [57]:
recommendations

,title,companyName,location,skill_match,experience_score,location_score,final_score,skill_gaps
45144,Data Engineer - Snowflake,Prudent Globaltech Solutions,Hyderabad,25.00,80,100,43.500,"[data manipulation, data warehousing, etl tool..."
8653,Big Data Engineer,Techno Facts Solutions,Remote,25.00,80,80,41.500,"[airflow, aws, data engineer, git, github, orc..."
44126,Opening For ETL Tester in Hyderabad location (...,Enrich And Enlight Business Consulting,Hyderabad,20.00,80,100,40.000,"[api, etl, etl testing, software testing]"
6546,Data Engineer Associate,Elfonze Technologies,"Hyderabad, Bengaluru",12.50,100,100,38.750,"[data governance, data integrity, data managem..."
52712,Trainee Data Engineer,Leewayhertz Technologies,Gurugram,25.00,100,0,37.500,"[aws, data engineer, data engineering, data pi..."
33882,Intern - Data Engineering,Exponentia Datalabs,Mumbai,25.00,100,0,37.500,"[analytical & problem-solving ability, analyti..."
80565,Business Technology Solutions Associate_ Cloud...,ZS,Pune,25.00,100,0,37.500,"[media, microservices, microsoft azure, rdbms,..."
10338,Trainee/Junior Data Engineer,Contata Solutions,Noida,25.00,100,0,37.500,"[bigquery fundamentals, cloud, git, python bas..."
60451,Data Engineer at An E-commerce Unicorn,Recruito,Remote,14.29,80,80,34.003,"[bricks, data, data bricks, e-commerce, kafka,..."
4078,Data Engineer|L1 Support|Noida,Talentonlease,"Noida, Mumbai",25.00,80,0,33.500,"[aws, data, data engineering, elt, etl, l1]"

In [59]:
import os

os.makedirs("../data/processed", exist_ok=True)

df_clean.to_pickle("../data/processed/jobs_clean.pkl")

print("Saved:", df_clean.shape)

Saved: (97682, 20)

In [60]:
recommendations.to_pickle(
    "../data/processed/recommendations.pkl"
)

print("Recommendations saved")

Recommendations saved

In [61]:
import sys
sys.path.append("..")

from src.recommender import recommend_jobs

In [62]:
test_recommendations = recommend_jobs(
    df=df_clean,
    candidate_skills=[
        "python",
        "sql",
        "pandas",
        "power bi"
    ],
    candidate_role="Data Engineering",
    candidate_location="Hyderabad",
    candidate_experience=0,
    top_n=10
)

In [63]:
test_recommendations[
    [
        "title",
        "companyName",
        "location",
        "skill_match",
        "experience_score",
        "location_score",
        "final_score",
        "skill_gaps"
    ]
]

,title,companyName,location,skill_match,experience_score,location_score,final_score,skill_gaps
45144,Data Engineer - Snowflake,Prudent Globaltech Solutions,Hyderabad,25.00,80,100,43.500,"[data manipulation, data warehousing, etl tool..."
8653,Big Data Engineer,Techno Facts Solutions,Remote,25.00,80,80,41.500,"[airflow, aws, data engineer, git, github, orc..."
44126,Opening For ETL Tester in Hyderabad location (...,Enrich And Enlight Business Consulting,Hyderabad,20.00,80,100,40.000,"[api, etl, etl testing, software testing]"
6546,Data Engineer Associate,Elfonze Technologies,"Hyderabad, Bengaluru",12.50,100,100,38.750,"[data governance, data integrity, data managem..."
10338,Trainee/Junior Data Engineer,Contata Solutions,Noida,25.00,100,0,37.500,"[bigquery fundamentals, cloud, git, python bas..."
80565,Business Technology Solutions Associate_ Cloud...,ZS,Pune,25.00,100,0,37.500,"[media, microservices, microsoft azure, rdbms,..."
52712,Trainee Data Engineer,Leewayhertz Technologies,Gurugram,25.00,100,0,37.500,"[aws, data engineer, data engineering, data pi..."
33882,Intern - Data Engineering,Exponentia Datalabs,Mumbai,25.00,100,0,37.500,"[analytical & problem-solving ability, analyti..."
60451,Data Engineer at An E-commerce Unicorn,Recruito,Remote,14.29,80,80,34.003,"[bricks, data, data bricks, e-commerce, kafka,..."
41423,Data Engineer,Seven N Consulting,Bengaluru,25.00,80,0,33.500,"[data analysis, data analytics, data warehousi..."

In [65]:
test_recommendations[
    ["skill_match", "experience_score", "location_score", "final_score"]
].isna().sum()

skill_match         0
experience_score    0
location_score      0
final_score         0
dtype: int64